apiVersion: v1
kind: LimitRange
metadata:
  name: limitador
spec:
  limits:
  - type: Container
    max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 100m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 64Mi
