apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolador
  namespace: raphael
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
